// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS_48Zw3y2m5BhZ1vqSQACsIjd36xaR2o',
    appId: '1:1082443809392:web:08cea15ff2455c9e8deab5',
    messagingSenderId: '1082443809392',
    projectId: 'area-om',
    authDomain: 'area-om.firebaseapp.com',
    storageBucket: 'area-om.appspot.com',
    measurementId: 'G-YLDGSLQMGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hWZLpgBQuSvgusujzoxyj-0ZBo9VZYE',
    appId: '1:1082443809392:android:98128ae7746959848deab5',
    messagingSenderId: '1082443809392',
    projectId: 'area-om',
    storageBucket: 'area-om.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwFZUU8gUzRa19CpKhlH0ks-PsBeUpibs',
    appId: '1:1082443809392:ios:e3d0e9d7189003478deab5',
    messagingSenderId: '1082443809392',
    projectId: 'area-om',
    storageBucket: 'area-om.appspot.com',
    iosClientId: '1082443809392-3qhu856ak1o0spa07uvag51a13amm1pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwFZUU8gUzRa19CpKhlH0ks-PsBeUpibs',
    appId: '1:1082443809392:ios:e3d0e9d7189003478deab5',
    messagingSenderId: '1082443809392',
    projectId: 'area-om',
    storageBucket: 'area-om.appspot.com',
    iosClientId: '1082443809392-3qhu856ak1o0spa07uvag51a13amm1pf.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
