# React Dockerfile

# Node base image
FROM node:latest

# Set working directory
WORKDIR /app

# Install http-server
RUN npm install -g http-server

# Copy package.json and package-lock.json
COPY ./web/package*.json ./

# Install dependencies and launch react app in the container
ENTRYPOINT ["./entrypoint.sh"]
