# Express Dockerfile

# Node base image
FROM node:latest

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./server/package*.json ./

# Install dependencies and launch express server
CMD [ "sh", "-c", "npm install --legacy-peer-deps && npm start" ]
