# React native Dockerfile

# Base image
FROM reactnativecommunity/react-native-android:latest

# Set working directory
WORKDIR /app

# Copy project files
COPY ./app/ ./

# Install expo-cli
RUN npm install --global @expo/ngrok@^4.1.0

# Install dependencies and launch react native application
ENTRYPOINT [ "./entrypoint.sh" ]
